var Photo_cjl=[
    {
        photoName_cjl:"img01",
        PhotoManagements_cjl: "../images/cjl/01.jpg",
        photoHuo_cjl:"小朋友乐园",
        photoIntroduction:"小朋友过生日",
        photoBan_cjl:"大班",
    },
    {
        photoName_cjl:"img02",
        PhotoManagements_cjl: "../images/cjl/02.jpeg",
        photoHuo_cjl:"户外活动",
        photoIntroduction:"野营画画",
        photoBan_cjl:"小班",
    },
    {
        photoName_cjl:"img03",
        PhotoManagements_cjl: "../images/cjl/03.jpg",
        photoHuo_cjl:"课堂时刻",
        photoIntroduction:"排排坐听讲讲",
        photoBan_cjl:"小班",
    },
    {
        photoName_cjl:"img04",
        PhotoManagements_cjl: "../images/cjl/04.jpg",
        photoHuo_cjl:"课堂时刻",
        photoIntroduction:"亲子互动",
        photoBan_cjl:"大班",
    },
    {
        photoName_cjl:"img05",
        PhotoManagements_cjl: "../images/cjl/05.jpg",
        photoHuo_cjl:"校园活动",
        photoIntroduction:"欢乐早操",
        photoBan_cjl:"大班",
    },
    {
        photoName_cjl:"img06",
        PhotoManagements_cjl: "../images/cjl/06.jpg",
        photoHuo_cjl:"小朋友乐园",
        photoIntroduction:"玩耍中的小朋友",
        photoBan_cjl:"小班",
    },
    {
        photoName_cjl:"img07",
        PhotoManagements_cjl: "../images/cjl/07.jpg",
        photoHuo_cjl:"毕业小朋友",
        photoIntroduction:"小朋友的纪念照片",
        photoBan_cjl:"大班",
    },
    {
        photoName_cjl:"img08",
        PhotoManagements_cjl: "../images/cjl/08.jpg",
        photoHuo_cjl:"校园活动",
        photoIntroduction:"篮球大赛",
        photoBan_cjl:"大班",
    },
    {
        photoName_cjl:"img09",
        PhotoManagements_cjl: "../images/cjl/09.jpg",
        photoHuo_cjl:"毕业小朋友",
        photoIntroduction:"小朋友创意照片",
        photoBan_cjl:"大班",
    },
    {
        photoName_cjl:"img10",
        PhotoManagements_cjl: "../images/cjl/10.jpg",
        photoHuo_cjl:"上课时刻",
        photoIntroduction:"听课中的小朋友",
        photoBan_cjl:"小班",
    },
    {
        photoName_cjl:"img11",
        PhotoManagements_cjl: "../images/cjl/11.jpg",
        photoHuo_cjl:"毕业小朋友",
        photoIntroduction:"小朋友的创意照片",
        photoBan_cjl:"大班",
    },
    {
        photoName_cjl:"img12",
        PhotoManagements_cjl: "../images/cjl/12.jpg",
        photoHuo_cjl:"超可爱小朋友",
        photoIntroduction:"不解释，超可爱",
        photoBan_cjl:"萌班",
    },
    {
        photoName_cjl:"img13",
        PhotoManagements_cjl: "../images/cjl/13.jpg",
        photoHuo_cjl:"课外实践",
        photoIntroduction:"认真做事的小朋友",
        photoBan_cjl:"大班",
    },
    {
        photoName_cjl:"img14",
        PhotoManagements_cjl: "../images/cjl/14.jpg",
        photoHuo_cjl:"课堂时刻",
        photoIntroduction:"排排坐听老师讲健康",
        photoBan_cjl:"小班",
    },
    {
        photoName_cjl:"img15",
        PhotoManagements_cjl: "../images/cjl/15.jpg",
        photoHuo_cjl:"课外实践",
        photoIntroduction:"小朋友自己动手做饭",
        photoBan_cjl:"大班",
    },
    {
        photoName_cjl:"img16",
        PhotoManagements_cjl: "../images/cjl/16.jpg",
        photoHuo_cjl:"校园活动",
        photoIntroduction:"校园活动小朋友都是花朵",
        photoBan_cjl:"小班",
    },
    {
        photoName_cjl:"img17",
        PhotoManagements_cjl: "../images/cjl/17.jpg",
        photoHuo_cjl:"课外实践",
        photoIntroduction:"小朋友课外活动实践",
        photoBan_cjl:"大班",
    },
    {
        photoName_cjl:"img18",
        PhotoManagements_cjl: "../images/cjl/18.jpg",
        photoHuo_cjl:"小朋友乐园",
        photoIntroduction:"小朋友在游戏",
        photoBan_cjl:"大班",
    },
    {
        photoName_cjl:"img19",
        PhotoManagements_cjl: "../images/cjl/19.jpg",
        photoHuo_cjl:"户外活动",
        photoIntroduction:"小朋友活泼可爱",
        photoBan_cjl:"大班",
    },
    {
        photoName_cjl:"img20",
        PhotoManagements_cjl: "../images/cjl/25.jpg",
        photoHuo_cjl:"小朋友乐园",
        photoIntroduction:"小朋友的画",
        photoBan_cjl:"小班",
    },
    {
        photoName_cjl:"img21",
        PhotoManagements_cjl: "../images/cjl/21.jpg",
        photoHuo_cjl:"户外活动",
        photoIntroduction:"小朋友课间游戏",
        photoBan_cjl:"大班",
    },
    {
        photoName_cjl:"img22",
        PhotoManagements_cjl: "../images/cjl/22.jpg",
        photoHuo_cjl:"户外活动",
        photoIntroduction:"活泼的小朋友",
        photoBan_cjl:"大班",
    },
    {
        photoName_cjl:"img23",
        PhotoManagements_cjl: "../images/cjl/23.jpg",
        photoHuo_cjl:"户外活动",
        photoIntroduction:"玩耍中的小朋友",
        photoBan_cjl:"大班",
    },
    {
        photoName_cjl:"img24",
        PhotoManagements_cjl: "../images/cjl/24.jpg",
        photoHuo_cjl:"校园活动",
        photoIntroduction:"篮球体操",
        photoBan_cjl:"大班",
    },
]